eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: 'http://${api.serviceRegistry.username}:${api.serviceRegistry.password}@localhost:8761/eureka'
server:
  port: 8761
spring:
  application:
    name: service-registry

api:
  serviceRegistry:
    username: serviceregistry
    password: '123sr'
    