spring:
  application:
    name: api-authuser
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        serviceId: config-server
      username: configserver
      password: '123cs'
